Repository hazelcast/imdg-docs, pull requests merged in 2021-03, with the labels that each got.

#84 Add management-permission description
  docs/modules/security/pages/native-client-security.adoc
Labels: content enhancement

#128 Fixes #122
  docs/modules/sql/pages/select-statement.adoc
Labels: bug, content enhancement

#129 Fixes #120
  docs/modules/data-structures/pages/map.adoc
  docs/modules/query/pages/how-distributed-query-works.adoc
Labels: bug, content enhancement

#130 Fixes #47
  docs/modules/ROOT/pages/index.adoc
Labels: content enhancement

#132 Updating the phone home information.
  docs/modules/ROOT/pages/phone-homes.adoc
Labels: missing content
